<template>
  <ul class="content">
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
    <li>分类的列表</li>
  </ul>
</template>

<script>
export default {
  name: 'Category'
}
</script>

<style scoped>
.content {
  height: 150px;
  background-color: red;

  /* overflow: hidden; */
  overflow-y: scroll;
}
</style>
